apiVersion: v1
kind: Namespace
metadata:
  name: consumer-dev
  labels:
    name: consumer-dev

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: consumer-dev
type: Opaque
stringData:
  minio_host: minio-deployment.minio-dev.svc.cluster.local:9000
  minio_access_key: B8l42QhLpcgoAE8eWg5W
  minio_secret_key: NkjBqwBzXfuXZbit6C3ZKrszWYD8BSFyhkEz0zD9
  minio_bucket_name: nst-bucket

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: consumer-dev
  name: nst-consumer-deployment
  labels:
    app.kubernetes.io/name: nst-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nst-consumer
  template:
    metadata:
      labels:
        app: nst-consumer
    spec:
      containers:
      - name: nst-consumer
        image: nst_consumer_image
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_HOST
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: minio_host
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: minio_access_key
        - name: MINIO_SECRET_KEY    
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: minio_secret_key
        - name: MINIO_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: minio_bucket_name